# .bashrc

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ll='ls -l'

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# pip warning ignore
export PIP_ROOT_USER_ACTION=ignore
export PIP_DISABLE_PIP_VERSION_CHECK=1

# node build env for mgr/dashboard
export NODE_MIRROR="https://npmmirror.com/mirrors/node"
export NPM_REGISTRY="https://registry.npmmirror.com"
export CYPRESS_DOWNLOAD_PATH_TEMPLATE="https://registry.npmmirror.com/-/binary/cypress/\${version}/\${platform}-\${arch}/cypress.zip"

# git proxy cmds
lsgitproxy() {
    echo "cmd: git proxy cmd."
    echo "    1. setgitproxy: enable github proxy of https://mirror.ghproxy.com/"
    echo "    2. delgitproxy: disable github proxy of https://mirror.ghproxy.com/"
    echo ""
}
setgitproxy() {
    delgitproxy
    git config --global url."https://mirror.ghproxy.com/https://github.com/".insteadOf https://github.com/
    echo "set github proxy: $(git config --global --get-regexp '^url.*insteadof$')"
}
delgitproxy() {
    proxies=$(git config --global --get-regexp '^url.*insteadof$' | awk -F ' ' '{print $1}')
    if test ! -z "$proxies"; then
        for proxy in "${proxies[@]}"; do
            key=$proxy
            val=$(git config --global --get $key)
            git config --global --unset $key
            echo "delete github proxy: $key $val"
        done
    fi
}

# set/unset ceph dep mirror
setcephdepmirror() {
    sed -i 's/https:\/\/registry.npmjs.org/https:\/\/registry.npmmirror.com/g' \
        /root/ceph/src/pybind/mgr/dashboard/frontend/package-lock.json || echo 0
    sed -i 's/https:\/\/boostorg.jfrog.io\/artifactory\/main\/release\/\$boost_version\/source/https:\/\/mirrors.aliyun.com\/blfs\/conglomeration\/boost/g' \
        /root/ceph/make-dist || echo 0
    sed -i 's/https:\/\/boostorg.jfrog.io\/artifactory\/main\/release\/\${boost_version}\/source/https:\/\/mirrors.aliyun.com\/blfs\/conglomeration\/boost/g' \
        /root/ceph/cmake/modules/BuildBoost.cmake || echo 0
}
unsetcephdepmirror() {
    sed -i 's/https:\/\/registry.npmmirror.com/https:\/\/registry.npmjs.org/g' \
        /root/ceph/src/pybind/mgr/dashboard/frontend/package-lock.json || echo 0
    sed -i 's/https:\/\/mirrors.aliyun.com\/blfs\/conglomeration\/boost/https:\/\/boostorg.jfrog.io\/artifactory\/main\/release\/\$boost_version\/source/g' \
        /root/ceph/make-dist || echo 0
    sed -i 's/https:\/\/mirrors.aliyun.com\/blfs\/conglomeration\/boost/https:\/\/boostorg.jfrog.io\/artifactory\/main\/release\/\${boost_version}\/source/g' \
        /root/ceph/cmake/modules/BuildBoost.cmake || echo 0
}

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
